---
- name: Install required system packages
  apt:
    name:
      - apt-transport-https 
      - ca-certificates 
      - curl 
      - gpg
    state: present

- name: Download Docker GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Register Docker repository
  template:
    src: docker.list.j2
    dest: /etc/apt/sources.list.d/docker.list
  notify: Update apt cache

- name: Apt update
  apt:
    update_cache: yes

- name: Install docker
  apt: 
    name:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io
      - docker-compose-plugin
    state: present

- name: Create symbolic link for docker-compose
  file:
    src: /usr/libexec/docker/cli-plugins/docker-compose
    dest: /bin/docker-compose
    state: link

# проверка установки
- name: Check Docker version
  command: docker --version
  register: docker_version_output

- name: Check Docker Compose version
  command: docker-compose --version
  register: docker_compose_version_output

- name: Output Docker version
  debug:
    msg: "{{ docker_version_output.stdout }}"

- name: Output Docker Compose version
  debug:
    msg: "{{ docker_compose_version_output.stdout }}"
...